### ISSUE TITLE
Api for Magic Cube?

### ISSUE THREAD

**Issue by Danielhiversen** [louisZL/lumi-gateway-local-api#3]
Do you have an api documentation for magic cube?

http://xiaomi-mi.com/mi-smart-home/xiaomi-mi-smart-home-cube-white/

**Comment by SublimePotato** [comment]
Since @louisZL wasn't active for 2 months, here's something that may be helpful: 

By now the gateway sends the device's heartbeat as described. 
https://github.com/louisZL/lumi-gateway-local-api/blob/635599c8776c44e730229355e92e40b8a3cc86ab/device_heartbeat.md

Since the cube is nothing more, than a fancy switch, you should be able to receive a multicast package für the cube as well. Sadly I don't own a cube myself so I can't tell in detail. I'm quite sure tho that they implemented the cube the same way.

**Comment by geeknam** [comment]
I have a cube and when calling get_id_list it shows as "model": "".
It replies to "read" commands
